class_name FingerMap
extends Resource
## The GDD touch-typing table (US QWERTY, GDD A1): which finger types each character. Authored once in
## data/finger_map.tres (generated by tools/gen_finger_map.gd); ZombieHands is the only user (FR15-FR18).
## Capitals and shifted symbols are stored with shift = 1 and their base key's finger; the lookup adds
## the opposite hand's pinky for Shift (FR17). Space is stored once, on the left thumb; the lookup adds
## the right thumb.

enum Hand { LEFT, RIGHT }
enum Finger { PINKY, RING, MIDDLE, INDEX, THUMB }

## Character -> Vector3i(hand, finger, shift 0/1).
@export var entries: Dictionary[String, Vector3i] = {}


## The fingers for one character, the character's own finger first, then its partner (the other thumb
## for Space, the opposite pinky for a shifted character). "" (no target) gives [] silently; anything
## else unmapped, or longer than one character, gives [] with a warning.
func fingers_for(c: String) -> Array[Vector2i]:
	var result: Array[Vector2i] = []
	if c == "":
		return result
	if c.length() != 1:
		Log.warn(&"hands", "fingers_for() needs one character, got '%s'" % c)
		return result
	if not entries.has(c):
		Log.warn(&"hands", "no finger mapping for '%s'" % c)
		return result
	var entry: Vector3i = entries[c]
	result.append(Vector2i(entry.x, entry.y))
	var other_hand: int = Hand.RIGHT if entry.x == Hand.LEFT else Hand.LEFT
	if entry.y == Finger.THUMB:
		result.append(Vector2i(other_hand, Finger.THUMB))
	elif entry.z == 1:
		result.append(Vector2i(other_hand, Finger.PINKY))
	return result


## 0-9: left pinky .. left thumb, then right pinky .. right thumb.
static func finger_id(hand_finger: Vector2i) -> int:
	return hand_finger.x * Finger.size() + hand_finger.y
